spring.application.name=paytrack

spring.datasource.url=jdbc:postgresql://localhost:5432/paytrack
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update